# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gooduiyay.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5.QtWidgets import QDialog, QApplication, QPushButton, QVBoxLayout
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
import matplotlib.pyplot as plt
import random
from tab_backends.analysis_functions.graphs_generic import genericGraph
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtSvg import QSvgWidget
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QWidget
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5.QtCore import QUrl
from PyQt5.QtWebEngineWidgets import QWebEngineView
import os

html_path = os.path.abspath("tab_backends/molecule_viewer_functions/viewer.html")

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # === Main Window Initialization ===
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 651)
        
        # === Central Widget and Main Layout Setup ===
        self.MainCentralWidget = QtWidgets.QWidget(MainWindow)
        self.MainCentralWidget.setObjectName("MainCentralWidget")
        self.MainCentralGridLayout = QtWidgets.QGridLayout(self.MainCentralWidget)
        self.MainCentralGridLayout.setObjectName("MainCentralGridLayout")

        # === Stacked Widget to Hold Different Layout Screens ===
        self.AppLayoutsHolderStackedWidget = QtWidgets.QStackedWidget(self.MainCentralWidget)
        self.AppLayoutsHolderStackedWidget.setObjectName("AppLayoutsHolderStackedWidget")

                # === Homescreen Setup ===
        self.Homescreen = QtWidgets.QWidget()
        self.Homescreen.setObjectName("Homescreen")
        self.HomescreenGridLayout = QtWidgets.QGridLayout(self.Homescreen)
        self.HomescreenGridLayout.setObjectName("HomescreenGridLayout")

        # === Homescreen SVG Display Section ===
        self.HomescreenSVGHolderWidget = QtWidgets.QWidget(self.Homescreen)
        self.HomescreenSVGHolderWidget.setObjectName("HomescreenSVGHolderWidget")
        self.HomescreenTextSVGLayout = QtWidgets.QVBoxLayout(self.HomescreenSVGHolderWidget)
        self.HomescreenTextSVGLayout.setObjectName("HomescreenTextSVGLayout")
        self.HomescreenSVGHolder = QSvgWidget("ui_and_style/1.svg", self.HomescreenSVGHolderWidget)
        self.HomescreenSVGHolder.setObjectName("HomescreenSVGHolder")
        self.HomescreenTextSVGLayout.addWidget(self.HomescreenSVGHolder)
        self.HomescreenGridLayout.addWidget(self.HomescreenSVGHolderWidget, 0, 0)

        # === Homescreen Button Section ===
        self.HomescreenButtonWidget = QtWidgets.QWidget(self.Homescreen)
        self.HomescreenButtonWidget.setObjectName("HomescreenButtonWidget")
        self.HomescreenButtonLayout = QtWidgets.QVBoxLayout(self.HomescreenButtonWidget)
        self.HomescreenButtonLayout.setObjectName("HomescreenButtonLayout")
        self.HomescreenLoadPybraneButton = QtWidgets.QPushButton(self.HomescreenButtonWidget)
        self.HomescreenLoadPybraneButton.setObjectName("HomescreenLoadPybraneButton")
        self.HomescreenButtonLayout.addWidget(self.HomescreenLoadPybraneButton)
        self.HomescreenOpenManualButton = QtWidgets.QPushButton(self.HomescreenButtonWidget)
        self.HomescreenOpenManualButton.setObjectName("HomescreenOpenManualButton")
        self.HomescreenButtonLayout.addWidget(self.HomescreenOpenManualButton)
        self.HomescreenSettingsButton = QtWidgets.QPushButton(self.HomescreenButtonWidget)
        self.HomescreenSettingsButton.setObjectName("HomescreenSettingsButton")
        self.HomescreenButtonLayout.addWidget(self.HomescreenSettingsButton)
        self.HomescreenCreditsButton = QtWidgets.QPushButton(self.HomescreenButtonWidget)
        self.HomescreenCreditsButton.setObjectName("HomescreenCreditsButton")
        self.HomescreenButtonLayout.addWidget(self.HomescreenCreditsButton)
        self.HomescreenGridLayout.addWidget(self.HomescreenButtonWidget, 0, 1)

        # === Set Stretch to Create 75/25 Ratio ===
        self.HomescreenGridLayout.setColumnStretch(0, 3)  # SVG section
        self.HomescreenGridLayout.setColumnStretch(1, 1)  # Button section

        # === Add Homescreen to Stacked Widget ===
        self.AppLayoutsHolderStackedWidget.addWidget(self.Homescreen)

        # === PyBRANE Main Layout ===
        self.PyBRANE = QtWidgets.QWidget()
        self.PyBRANE.setObjectName("PyBRANE")
        self.PyBRANEAppGridLayout = QtWidgets.QGridLayout(self.PyBRANE)
        self.PyBRANEAppGridLayout.setObjectName("PyBRANEAppGridLayout")

        # === PyBRANE Right-Side Panel (Notes & Help Tabs) ===
        self.PybraneRightWidget = QtWidgets.QWidget(self.PyBRANE)
        self.PybraneRightWidget.setObjectName("PybraneRightWidget")
        self.PybraneRightLayout = QtWidgets.QVBoxLayout(self.PybraneRightWidget)
        self.PybraneRightLayout.setObjectName("PybraneRightLayout")

        # === PyBRANE Notes and Help Tab Widget ===
        self.PybraneNotesAndHelpWidget = QtWidgets.QTabWidget(self.PybraneRightWidget)
        self.PybraneNotesAndHelpWidget.setObjectName("PybraneNotesAndHelpWidget")

        # === PyBRANE Notes Tab ===
        self.PybraneNotesWidget = QtWidgets.QWidget()
        self.PybraneNotesWidget.setObjectName("PybraneNotesWidget")
        self.PybraneNotesLayout = QtWidgets.QGridLayout(self.PybraneNotesWidget)
        self.PybraneNotesLayout.setObjectName("PybraneNotesLayout")
        self.PybraneNotesTextBox = QtWidgets.QPlainTextEdit(self.PybraneNotesWidget)
        self.PybraneNotesTextBox.setObjectName("PybraneNotesTextBox")
        self.PybraneNotesLayout.addWidget(self.PybraneNotesTextBox, 0, 0, 1, 1)
        self.PybraneNotesAndHelpWidget.addTab(self.PybraneNotesWidget, "")

        # === PyBRANE Help Tab with ToolBox Sections ===
        self.PybraneHelpTab = QtWidgets.QWidget()
        self.PybraneHelpTab.setObjectName("PybraneHelpTab")
        self.PybraneHelpLayout = QtWidgets.QGridLayout(self.PybraneHelpTab)
        self.PybraneHelpLayout.setObjectName("PybraneHelpLayout")
        self.PybraneHelpDropdown = QtWidgets.QToolBox(self.PybraneHelpTab)
        self.PybraneHelpDropdown.setObjectName("PybraneHelpDropdown")
        
        self.PybraneLessonTab = QtWidgets.QWidget()
        self.PybraneLessonTab.setObjectName("PybraneLessonTab")
        self.PybraneLessonTabGridLayout = QtWidgets.QGridLayout(self.PybraneLessonTab)
        self.PybraneLessonTabGridLayout.setObjectName("PybraneLessonTabGridLayout")
        self.PybraneLessonTabLessonSelectorWidget = QtWidgets.QWidget(self.PybraneLessonTab)
        self.PybraneLessonTabLessonSelectorWidget.setObjectName("PybraneLessonTabLessonSelectorWidget")
        self.PybraneLessonTabLessonSelectionGridLayout = QtWidgets.QGridLayout(self.PybraneLessonTabLessonSelectorWidget)
        self.PybraneLessonTabLessonSelectionGridLayout.setObjectName("PybraneLessonTabLessonSelectionGridLayout")
        self.PybraneLessonTabLevelLabel = QtWidgets.QLabel(self.PybraneLessonTabLessonSelectorWidget)
        self.PybraneLessonTabLevelLabel.setObjectName("PybraneLessonTabLevelLabel")
        self.PybraneLessonTabLessonSelectionGridLayout.addWidget(self.PybraneLessonTabLevelLabel, 0, 0, 1, 1)
        self.PybraneLessonTabUnitLabel = QtWidgets.QLabel(self.PybraneLessonTabLessonSelectorWidget)
        self.PybraneLessonTabUnitLabel.setObjectName("PybraneLessonTabUnitLabel")
        self.PybraneLessonTabLessonSelectionGridLayout.addWidget(self.PybraneLessonTabUnitLabel, 0, 1, 1, 1)
        self.PybraneLessonTabLessonLabel = QtWidgets.QLabel(self.PybraneLessonTabLessonSelectorWidget)
        self.PybraneLessonTabLessonLabel.setObjectName("PybraneLessonTabLessonLabel")
        self.PybraneLessonTabLessonSelectionGridLayout.addWidget(self.PybraneLessonTabLessonLabel, 0, 2, 1, 1)
        self.PybraneLessonTabLevelComboBox = QtWidgets.QSpinBox(self.PybraneLessonTabLessonSelectorWidget)
        self.PybraneLessonTabLevelComboBox.setObjectName("PybraneLessonTabLevelComboBox")
        self.PybraneLessonTabLessonSelectionGridLayout.addWidget(self.PybraneLessonTabLevelComboBox, 1, 0, 1, 1)
        self.PybraneLessonTabUnitComboBox = QtWidgets.QSpinBox(self.PybraneLessonTabLessonSelectorWidget)
        self.PybraneLessonTabUnitComboBox.setObjectName("PybraneLessonTabUnitComboBox")
        self.PybraneLessonTabLessonSelectionGridLayout.addWidget(self.PybraneLessonTabUnitComboBox, 1, 1, 1, 1)
        self.PybraneLessonTabLessonComboBox = QtWidgets.QSpinBox(self.PybraneLessonTabLessonSelectorWidget)
        self.PybraneLessonTabLessonComboBox.setObjectName("PybraneLessonTabLessonComboBox")
        self.PybraneLessonTabLessonSelectionGridLayout.addWidget(self.PybraneLessonTabLessonComboBox, 1, 2, 1, 1)
        self.PybraneLessonTabGridLayout.addWidget(self.PybraneLessonTabLessonSelectorWidget, 0, 0, 1, 1)
        self.PybraneLessonHolderStackedWidget = QtWidgets.QStackedWidget(self.PybraneLessonTab)
        self.PybraneLessonHolderStackedWidget.setObjectName("PybraneLessonHolderStackedWidget")
        self.PybraneLessonTabLesson1Layout = QtWidgets.QWidget()
        self.PybraneLessonTabLesson1Layout.setObjectName("PybraneLessonTabLesson1Layout")
        self.PybraneLessonTabLesson1GridLayout = QtWidgets.QGridLayout(self.PybraneLessonTabLesson1Layout)
        self.PybraneLessonTabLesson1GridLayout.setObjectName("PybraneLessonTabLesson1GridLayout")
        self.PybraneLessonTabLesson1TextBox = QtWidgets.QTextBrowser(self.PybraneLessonTabLesson1Layout)
        self.PybraneLessonTabLesson1TextBox.setObjectName("PybraneLessonTabLesson1TextBox")
        self.PybraneLessonTabLesson1GridLayout.addWidget(self.PybraneLessonTabLesson1TextBox, 1, 0, 1, 1)
        self.PybraneLessonHolderStackedWidget.addWidget(self.PybraneLessonTabLesson1Layout)
        self.PybraneLessonTabLesson2Layout = QtWidgets.QWidget()
        self.PybraneLessonTabLesson2Layout.setObjectName("PybraneLessonTabLesson2Layout")
        self.PybraneLessonTabLesson2GridLayout = QtWidgets.QGridLayout(self.PybraneLessonTabLesson2Layout)
        self.PybraneLessonTabLesson2GridLayout.setObjectName("PybraneLessonTabLesson2GridLayout")
        self.PybraneLessonTabLesson2TextBox = QtWidgets.QTextBrowser(self.PybraneLessonTabLesson2Layout)
        self.PybraneLessonTabLesson2TextBox.setObjectName("PybraneLessonTabLesson2TextBox")
        self.PybraneLessonTabLesson2GridLayout.addWidget(self.PybraneLessonTabLesson2TextBox, 0, 0, 1, 1)
        self.PybraneLessonHolderStackedWidget.addWidget(self.PybraneLessonTabLesson2Layout)
        self.PybraneLessonTabLesson3Layout = QtWidgets.QWidget()
        self.PybraneLessonTabLesson3Layout.setObjectName("PybraneLessonTabLesson3Layout")
        self.PybraneLessonTabLesson3GridLayout = QtWidgets.QGridLayout(self.PybraneLessonTabLesson3Layout)
        self.PybraneLessonTabLesson3GridLayout.setObjectName("PybraneLessonTabLesson3GridLayout")
        self.PybraneLessonTabLesson3TextBox = QtWidgets.QTextBrowser(self.PybraneLessonTabLesson3Layout)
        self.PybraneLessonTabLesson3TextBox.setObjectName("PybraneLessonTabLesson3TextBox")
        self.PybraneLessonTabLesson3GridLayout.addWidget(self.PybraneLessonTabLesson3TextBox, 0, 0, 1, 1)
        self.PybraneLessonHolderStackedWidget.addWidget(self.PybraneLessonTabLesson3Layout)
        self.PybraneLessonTabLesson4Layout = QtWidgets.QWidget()
        self.PybraneLessonTabLesson4Layout.setObjectName("PybraneLessonTabLesson4Layout")
        self.PybraneLessonTabLesson4GridLayout = QtWidgets.QGridLayout(self.PybraneLessonTabLesson4Layout)
        self.PybraneLessonTabLesson4GridLayout.setObjectName("PybraneLessonTabLesson4GridLayout")
        self.PybraneLessonTabLesson4TextBox = QtWidgets.QTextBrowser(self.PybraneLessonTabLesson4Layout)
        self.PybraneLessonTabLesson4TextBox.setObjectName("PybraneLessonTabLesson4TextBox")
        self.PybraneLessonTabLesson4GridLayout.addWidget(self.PybraneLessonTabLesson4TextBox, 0, 0, 1, 1)
        self.PybraneLessonHolderStackedWidget.addWidget(self.PybraneLessonTabLesson4Layout)
        self.PybraneLessonTabLesson5Layout = QtWidgets.QWidget()
        self.PybraneLessonTabLesson5Layout.setObjectName("PybraneLessonTabLesson5Layout")
        self.PybraneLessonTabLesson5GridLayout = QtWidgets.QGridLayout(self.PybraneLessonTabLesson5Layout)
        self.PybraneLessonTabLesson5GridLayout.setObjectName("PybraneLessonTabLesson5GridLayout")
        self.PybraneLessonTabLesson5TextBox = QtWidgets.QTextBrowser(self.PybraneLessonTabLesson5Layout)
        self.PybraneLessonTabLesson5TextBox.setObjectName("PybraneLessonTabLesson5TextBox")
        self.PybraneLessonTabLesson5GridLayout.addWidget(self.PybraneLessonTabLesson5TextBox, 0, 0, 1, 1)
        self.PybraneLessonHolderStackedWidget.addWidget(self.PybraneLessonTabLesson5Layout)
        self.PybraneLessonTabGridLayout.addWidget(self.PybraneLessonHolderStackedWidget, 1, 0, 1, 1)
        self.PybraneNotesAndHelpWidget.addTab(self.PybraneLessonTab, "")
        self.PybraneMichaelTab = QtWidgets.QWidget()
        self.PybraneMichaelTab.setObjectName("PybraneMichaelTab")
        self.PybraneMichaelGridLayout = QtWidgets.QGridLayout(self.PybraneMichaelTab)
        self.PybraneMichaelGridLayout.setObjectName("PybraneMichaelGridLayout")
        self.PybraneMichaelUserInputLineEdit = QtWidgets.QLineEdit(self.PybraneMichaelTab)
        self.PybraneMichaelUserInputLineEdit.setObjectName("PybraneMichaelUserInputLineEdit")
        self.PybraneMichaelGridLayout.addWidget(self.PybraneMichaelUserInputLineEdit, 1, 0, 2, 1)
        self.PybraneMichaelEnterButton = QtWidgets.QPushButton(self.PybraneMichaelTab)
        self.PybraneMichaelEnterButton.setObjectName("PybraneMichaelEnterButton")
        self.PybraneMichaelGridLayout.addWidget(self.PybraneMichaelEnterButton, 2, 1, 1, 1)
        self.PybraneMichaelResponseTextBox = QtWidgets.QTextBrowser(self.PybraneMichaelTab)
        self.PybraneMichaelResponseTextBox.setObjectName("PybraneMichaelResponseTextBox")
        self.PybraneMichaelGridLayout.addWidget(self.PybraneMichaelResponseTextBox, 0, 0, 1, 2)
        self.PybraneNotesAndHelpWidget.addTab(self.PybraneMichaelTab, "")
        self.PybraneRightLayout.addWidget(self.PybraneNotesAndHelpWidget)
        self.PyBRANEAppGridLayout.addWidget(self.PybraneRightWidget, 0, 3, 1, 1)

        # === PyBRANE Left Panel : File Search Tab ===
        self.PybraneLeftWidget = QtWidgets.QTabWidget(self.PyBRANE)
        self.PybraneLeftWidget.setObjectName("PybraneLeftWidget")
        self.PybraneFileTab = QtWidgets.QWidget()
        self.PybraneFileTab.setObjectName("PybraneFileTab")
        self.PybraneFileTabGridLayout = QtWidgets.QGridLayout(self.PybraneFileTab)
        self.PybraneFileTabGridLayout.setObjectName("PybraneFileTabGridLayout")

        # === File Tab : Instructions and Query Entry ===
        self.PybraneFileTabInstructionTextBox = QtWidgets.QTextBrowser(self.PybraneFileTab)
        self.PybraneFileTabInstructionTextBox.setObjectName("PybraneFileTabInstructionTextBox")
        self.PybraneFileTabGridLayout.addWidget(self.PybraneFileTabInstructionTextBox, 0, 0, 1, 2)
        self.PybraneSearchQuearyLineEdit = QtWidgets.QLineEdit(self.PybraneFileTab)
        self.PybraneSearchQuearyLineEdit.setObjectName("PybraneSearchQuearyLineEdit")
        self.PybraneFileTabGridLayout.addWidget(self.PybraneSearchQuearyLineEdit, 1, 0, 1, 2)

        # === File Tab : ChemSpider Search ===
        self.PybraneChemSpiLabel = QtWidgets.QLabel(self.PybraneFileTab)
        self.PybraneChemSpiLabel.setObjectName("PybraneChemSpiLabel")
        self.PybraneFileTabGridLayout.addWidget(self.PybraneChemSpiLabel, 2, 0, 1, 1)
        self.PybraneChemSpiSearchButton = QtWidgets.QPushButton(self.PybraneFileTab)
        self.PybraneChemSpiSearchButton.setObjectName("PybraneChemSpiSearchButton")
        self.PybraneFileTabGridLayout.addWidget(self.PybraneChemSpiSearchButton, 2, 1, 1, 1)

        # === File Tab : Wikipedia Search ===
        self.PybraneWikipediaLabel = QtWidgets.QLabel(self.PybraneFileTab)
        self.PybraneWikipediaLabel.setObjectName("PybraneWikipediaLabel")
        self.PybraneFileTabGridLayout.addWidget(self.PybraneWikipediaLabel, 3, 0, 1, 1)
        self.PybraneWikipediaSearchButton = QtWidgets.QPushButton(self.PybraneFileTab)
        self.PybraneWikipediaSearchButton.setObjectName("PybraneWikipediaSearchButton")
        self.PybraneFileTabGridLayout.addWidget(self.PybraneWikipediaSearchButton, 3, 1, 1, 1)

        # === File Tab : PDB Search ===
        self.PybranePDBLabel = QtWidgets.QLabel(self.PybraneFileTab)
        self.PybranePDBLabel.setObjectName("PybranePDBLabel")
        self.PybraneFileTabGridLayout.addWidget(self.PybranePDBLabel, 4, 0, 1, 1)
        self.PybranePDBSearchButton = QtWidgets.QPushButton(self.PybraneFileTab)
        self.PybranePDBSearchButton.setObjectName("PybranePDBSearchButton")
        self.PybraneFileTabGridLayout.addWidget(self.PybranePDBSearchButton, 4, 1, 1, 1)

        # === File Tab : MemBank Search ===
        self.PybraneMemBankLabel = QtWidgets.QLabel(self.PybraneFileTab)
        self.PybraneMemBankLabel.setObjectName("PybraneMemBankLabel")
        self.PybraneFileTabGridLayout.addWidget(self.PybraneMemBankLabel, 5, 0, 1, 1)
        self.PybraneMemBankSearchButton = QtWidgets.QPushButton(self.PybraneFileTab)
        self.PybraneMemBankSearchButton.setObjectName("PybraneMemBankSearchButton")
        self.PybraneFileTabGridLayout.addWidget(self.PybraneMemBankSearchButton, 5, 1, 1, 1)

        # === File Tab : Folder Input and Debug Text ===
        self.PybraneFolderLineEdit = QtWidgets.QLineEdit(self.PybraneFileTab)
        self.PybraneFolderLineEdit.setObjectName("PybraneFolderLineEdit")
        self.PybraneFileTabGridLayout.addWidget(self.PybraneFolderLineEdit, 6, 0, 1, 2)
        self.PybraneFileTabDebugTextBox = QtWidgets.QTextBrowser(self.PybraneFileTab)
        self.PybraneFileTabDebugTextBox.setObjectName("PybraneFileTabDebugTextBox")
        self.PybraneFileTabGridLayout.addWidget(self.PybraneFileTabDebugTextBox, 7, 0, 1, 2)
        self.PybraneLeftWidget.addTab(self.PybraneFileTab, "")

        # === Shell Tab : Command Input and Output ===
        self.PybraneShellTab = QtWidgets.QWidget()
        self.PybraneShellTab.setObjectName("PybraneShellTab")
        self.PybraneShellTabGridLayout = QtWidgets.QGridLayout(self.PybraneShellTab)
        self.PybraneShellTabGridLayout.setObjectName("PybraneShellTabGridLayout")
        self.PybraneShellDebugTextBox = QtWidgets.QTextBrowser(self.PybraneShellTab)
        self.PybraneShellDebugTextBox.setObjectName("PybraneShellDebugTextBox")
        self.PybraneShellTabGridLayout.addWidget(self.PybraneShellDebugTextBox, 0, 0, 1, 2)
        self.PybraneShellEnterButton = QtWidgets.QPushButton(self.PybraneShellTab)
        self.PybraneShellEnterButton.setObjectName("PybraneShellEnterButton")
        self.PybraneShellTabGridLayout.addWidget(self.PybraneShellEnterButton, 1, 1, 1, 1)
        self.PybraneShellLineEdit = QtWidgets.QLineEdit(self.PybraneShellTab)
        self.PybraneShellLineEdit.setObjectName("PybraneShellLineEdit")
        self.PybraneShellTabGridLayout.addWidget(self.PybraneShellLineEdit, 1, 0, 1, 1)
        self.PybraneLeftWidget.addTab(self.PybraneShellTab, "")
        self.PyBRANEAppGridLayout.addWidget(self.PybraneLeftWidget, 0, 0, 1, 1)

        # === Center Widget : Molecular Viewer Tab ===
        self.PybraneCenterWidget = QtWidgets.QTabWidget(self.PyBRANE)
        self.PybraneCenterWidget.setObjectName("PybraneCenterWidget")

        # === Molecular Viewer : Tab and Layout ===
        self.PybraneMolViewerTab = QtWidgets.QWidget()
        self.PybraneMolViewerTab.setObjectName("PybraneMolViewerTab")
        self.PybraneMolViewerTabGridLayout = QtWidgets.QGridLayout(self.PybraneMolViewerTab)
        self.PybraneMolViewerTabGridLayout.setObjectName("PybraneMolViewerTabGridLayout")

        # === Molecular Viewer : View Holder (2D/3D Tabs) ===
        self.PybraneMolViewerViewHolderWidget = QtWidgets.QTabWidget(self.PybraneMolViewerTab)
        self.PybraneMolViewerViewHolderWidget.setObjectName("PybraneMolViewerViewHolderWidget")

        # === Molecular Viewer : 3D View ===
        self.PybraneMolViewer3DViewWidget = QtWidgets.QWidget()
        self.PybraneMolViewer3DViewWidget.setObjectName("PybraneMolViewer3DViewWidget")
        self.PybraneMolViewer3DViewGridLayout = QtWidgets.QGridLayout(self.PybraneMolViewer3DViewWidget)
        self.PybraneMolViewer3DViewGridLayout.setObjectName("PybraneMolViewer3DViewGridLayout")
        self.PybraneMolViewer3DViewJSViewer = QWebEngineView()
        self.PybraneMolViewer3DViewJSViewer.load(QUrl.fromLocalFile(html_path))
        self.PybraneMolViewer3DViewJSViewer.setObjectName("PybraneMolViewer3DViewJSViewer")
        self.PybraneMolViewer3DViewGridLayout.addWidget(self.PybraneMolViewer3DViewJSViewer, 0, 0, 1, 1)
        self.PybraneMolViewerViewHolderWidget.addTab(self.PybraneMolViewer3DViewWidget, "")

        # === Molecular Viewer : 2D View ===
        self.PybraneMolViewer2DViewWidget = QtWidgets.QWidget()
        self.PybraneMolViewer2DViewWidget.setObjectName("PybraneMolViewer2DViewWidget")
        self.PybraneMolViewer2DViewGridLayout = QtWidgets.QGridLayout(self.PybraneMolViewer2DViewWidget)
        self.PybraneMolViewer2DViewGridLayout.setObjectName("PybraneMolViewer2DViewGridLayout")
        self.PybraneMolViewer2DView = QtWidgets.QGraphicsScene()
        self.PybraneMolViewer2DView.setObjectName("PybraneMolViewer2DView")
        self.PybraneMolViewer2DViewScreen = QtWidgets.QGraphicsView(self.PybraneMolViewer2DView)
        self.PybraneMolViewer2DViewScreen.setObjectName("PybraneMolViewer2DViewScreen")
        self.PybraneMolViewer2DViewGridLayout.addWidget(self.PybraneMolViewer2DViewScreen, 0, 0, 1, 1)
        self.PybraneMolViewerViewHolderWidget.addTab(self.PybraneMolViewer2DViewWidget, "")
        self.PybraneMolViewerTabGridLayout.addWidget(self.PybraneMolViewerViewHolderWidget, 2, 0, 1, 2)

# === Molecular Viewer : Button Holder ===
        self.PybraneMolViewerButtonHolderWidget = QtWidgets.QWidget(self.PybraneMolViewerTab)
        self.PybraneMolViewerButtonHolderWidget.setObjectName("PybraneMolViewerButtonHolderWidget")
        self.PybraneMolViewerButtonHorizontalLayout = QtWidgets.QHBoxLayout(self.PybraneMolViewerButtonHolderWidget)
        self.PybraneMolViewerButtonHorizontalLayout.setObjectName("PybraneMolViewerButtonHorizontalLayout")

# === Molecular Viewer : Left Button Panel (File Import/Save) ===
        self.PybraneMolViewerLeftButtonHolderWidget = QtWidgets.QWidget(self.PybraneMolViewerButtonHolderWidget)
        self.PybraneMolViewerLeftButtonHolderWidget.setObjectName("PybraneMolViewerLeftButtonHolderWidget")
        self.PybraneMolViewerLeftVerticalLayout = QtWidgets.QVBoxLayout(self.PybraneMolViewerLeftButtonHolderWidget)
        self.PybraneMolViewerLeftVerticalLayout.setObjectName("PybraneMolViewerLeftVerticalLayout")
        self.PybraneMolViewerFileLabel = QtWidgets.QLabel(self.PybraneMolViewerLeftButtonHolderWidget)
        self.PybraneMolViewerFileLabel.setObjectName("PybraneMolViewerFileLabel")
        self.PybraneMolViewerLeftVerticalLayout.addWidget(self.PybraneMolViewerFileLabel)
        self.PybraneMolViewerSaveFileButton = QtWidgets.QPushButton(self.PybraneMolViewerLeftButtonHolderWidget)
        self.PybraneMolViewerSaveFileButton.setObjectName("PybraneMolViewerSaveFileButton")
        self.PybraneMolViewerLeftVerticalLayout.addWidget(self.PybraneMolViewerSaveFileButton)
        self.PybraneMolViewerImportSmilesButton = QtWidgets.QPushButton(self.PybraneMolViewerLeftButtonHolderWidget)
        self.PybraneMolViewerImportSmilesButton.setObjectName("PybraneMolViewerImportSmilesButton")
        self.PybraneMolViewerLeftVerticalLayout.addWidget(self.PybraneMolViewerImportSmilesButton)
        self.PybraneMolViewerLoadPDBButon = QtWidgets.QPushButton(self.PybraneMolViewerLeftButtonHolderWidget)
        self.PybraneMolViewerLoadPDBButon.setObjectName("PybraneMolViewerLoadPDBButon")
        self.PybraneMolViewerLeftVerticalLayout.addWidget(self.PybraneMolViewerLoadPDBButon)
        self.PybraneMolViewerButtonHorizontalLayout.addWidget(self.PybraneMolViewerLeftButtonHolderWidget)


# === Molecular Viewer : Central Button Panel (Edit Tools) ===
        self.PybraneMolViewerCentralButtonHolderWidget = QtWidgets.QWidget(self.PybraneMolViewerButtonHolderWidget)
        self.PybraneMolViewerCentralButtonHolderWidget.setObjectName("PybraneMolViewerCentralButtonHolderWidget")
        self.PybraneMolViewerCenterVerticalLayout = QtWidgets.QVBoxLayout(self.PybraneMolViewerCentralButtonHolderWidget)
        self.PybraneMolViewerCenterVerticalLayout.setObjectName("PybraneMolViewerCenterVerticalLayout")
        self.PybraneMolViewerEditLabel = QtWidgets.QLabel(self.PybraneMolViewerCentralButtonHolderWidget)
        self.PybraneMolViewerEditLabel.setObjectName("PybraneMolViewerEditLabel")
        self.PybraneMolViewerCenterVerticalLayout.addWidget(self.PybraneMolViewerEditLabel)
        self.PybraneMolViewerEditAtomsButton = QtWidgets.QPushButton(self.PybraneMolViewerCentralButtonHolderWidget)
        self.PybraneMolViewerEditAtomsButton.setObjectName("PybraneMolViewerEditAtomsButton")
        self.PybraneMolViewerCenterVerticalLayout.addWidget(self.PybraneMolViewerEditAtomsButton)
        self.PybraneMolViewerEditBondsButton = QtWidgets.QPushButton(self.PybraneMolViewerCentralButtonHolderWidget)
        self.PybraneMolViewerEditBondsButton.setObjectName("PybraneMolViewerEditBondsButton")
        self.PybraneMolViewerCenterVerticalLayout.addWidget(self.PybraneMolViewerEditBondsButton)
        self.PybraneMolViewerEditApperanceButton = QtWidgets.QPushButton(self.PybraneMolViewerCentralButtonHolderWidget)
        self.PybraneMolViewerEditApperanceButton.setObjectName("PybraneMolViewerEditApperanceButton")
        self.PybraneMolViewerCenterVerticalLayout.addWidget(self.PybraneMolViewerEditApperanceButton)
        self.PybraneMolViewerButtonHorizontalLayout.addWidget(self.PybraneMolViewerCentralButtonHolderWidget)

# === Molecular Viewer : Right Button Panel (Miscellaneous) ===
        self.PybraneMolViewerRightButtonHolderWidget = QtWidgets.QWidget(self.PybraneMolViewerButtonHolderWidget)
        self.PybraneMolViewerRightButtonHolderWidget.setObjectName("PybraneMolViewerRightButtonHolderWidget")
        self.PybraneMolViewerRightVerticalLayout = QtWidgets.QVBoxLayout(self.PybraneMolViewerRightButtonHolderWidget)
        self.PybraneMolViewerRightVerticalLayout.setObjectName("PybraneMolViewerRightVerticalLayout")
        self.PybraneMolViewerMiscLabel = QtWidgets.QLabel(self.PybraneMolViewerRightButtonHolderWidget)
        self.PybraneMolViewerMiscLabel.setObjectName("PybraneMolViewerMiscLabel")
        self.PybraneMolViewerRightVerticalLayout.addWidget(self.PybraneMolViewerMiscLabel)
        self.PybraneMolViewerSwitchDisplayButton = QtWidgets.QPushButton(self.PybraneMolViewerRightButtonHolderWidget)
        self.PybraneMolViewerSwitchDisplayButton.setObjectName("PybraneMolViewerSwtichDisplayButton")
        self.PybraneMolViewerRightVerticalLayout.addWidget(self.PybraneMolViewerSwitchDisplayButton)
        self.PybraneMolViewerSwitchFilesButton = QtWidgets.QPushButton(self.PybraneMolViewerRightButtonHolderWidget)
        self.PybraneMolViewerSwitchFilesButton.setObjectName("PybraneMolViewerSwitchFilesButton")
        self.PybraneMolViewerRightVerticalLayout.addWidget(self.PybraneMolViewerSwitchFilesButton)
        self.PybraneMolViewerExamplesButton = QtWidgets.QPushButton(self.PybraneMolViewerRightButtonHolderWidget)
        self.PybraneMolViewerExamplesButton.setObjectName("PybraneMolViewerExamplesButton")
        self.PybraneMolViewerRightVerticalLayout.addWidget(self.PybraneMolViewerExamplesButton)
        self.PybraneMolViewerButtonHorizontalLayout.addWidget(self.PybraneMolViewerRightButtonHolderWidget)
        self.PybraneMolViewerTabGridLayout.addWidget(self.PybraneMolViewerButtonHolderWidget, 3, 0, 1, 2)
        self.PybraneCenterWidget.addTab(self.PybraneMolViewerTab, "")

# === Membrane Maker : Main Tab ===
        self.PybraneMemMakerTab = QtWidgets.QWidget()
        self.PybraneMemMakerTab.setObjectName("PybraneMemMakerTab")
        self.PybraneMemMakerMainGridLayout = QtWidgets.QGridLayout(self.PybraneMemMakerTab)
        self.PybraneMemMakerMainGridLayout.setObjectName("PybraneMemMakerMainGridLayout")

# === Membrane Maker : Top Section (Debug & SVG Display) ===
        self.PybraneMemMakerTopWidget = QtWidgets.QWidget(self.PybraneMemMakerTab)
        self.PybraneMemMakerTopWidget.setObjectName("PybraneMemMakerTopWidget")
        self.PybraneMemMakerTopGridLayout = QtWidgets.QGridLayout(self.PybraneMemMakerTopWidget)
        self.PybraneMemMakerTopGridLayout.setObjectName("PybraneMemMakerTopGridLayout")
        self.PybraneMemMakerDebugTextBox = QtWidgets.QTextBrowser(self.PybraneMemMakerTopWidget)
        self.PybraneMemMakerDebugTextBox.setObjectName("PybraneMemMakerDebugTextBox")
        self.PybraneMemMakerTopGridLayout.addWidget(self.PybraneMemMakerDebugTextBox, 0, 1, 1, 1)
        self.PybraneMemMaker3DJSViewer = QWebEngineView()
        self.PybraneMemMaker3DJSViewer.load(QUrl.fromLocalFile(html_path))
        self.PybraneMemMaker3DJSViewer.setObjectName("PybraneMemMaker3DJSViewer")
        self.PybraneMemMakerTopGridLayout.addWidget(self.PybraneMemMaker3DJSViewer, 0, 0, 1, 1)
        self.PybraneMemMakerMainGridLayout.addWidget(self.PybraneMemMakerTopWidget, 0, 0, 1, 2)

# === Membrane Maker : Measurements Section ===
        self.PybraneMemMakerMeasurmentsWidget = QtWidgets.QWidget(self.PybraneMemMakerTab)
        self.PybraneMemMakerMeasurmentsWidget.setObjectName("PybraneMemMakerMeasurmentsWidget")
        self.PybraneMemMakerMeasurementsGridLayout = QtWidgets.QGridLayout(self.PybraneMemMakerMeasurmentsWidget)
        self.PybraneMemMakerMeasurementsGridLayout.setObjectName("PybraneMemMakerMeasurementsGridLayout")

# === Membrane Maker : Measurement Labels ===
        self.PybraneMemMakerXLabel = QtWidgets.QLabel(self.PybraneMemMakerMeasurmentsWidget)
        self.PybraneMemMakerXLabel.setObjectName("PybraneMemMakerXLabel")
        self.PybraneMemMakerMeasurementsGridLayout.addWidget(self.PybraneMemMakerXLabel, 1, 0, 1, 1)

        self.PybraneMemMakerYLabel = QtWidgets.QLabel(self.PybraneMemMakerMeasurmentsWidget)
        self.PybraneMemMakerYLabel.setObjectName("PybraneMemMakerYLabel")
        self.PybraneMemMakerMeasurementsGridLayout.addWidget(self.PybraneMemMakerYLabel, 2, 0, 1, 1)

        self.PybraneMemMakerZLabel = QtWidgets.QLabel(self.PybraneMemMakerMeasurmentsWidget)
        self.PybraneMemMakerZLabel.setObjectName("PybraneMemMakerZLabel")
        self.PybraneMemMakerMeasurementsGridLayout.addWidget(self.PybraneMemMakerZLabel, 3, 0, 3, 1)

        self.PybraneMemMakerMeasurementsLabel = QtWidgets.QLabel(self.PybraneMemMakerMeasurmentsWidget)
        self.PybraneMemMakerMeasurementsLabel.setObjectName("PybraneMemMakerMeasurementsLabel")
        self.PybraneMemMakerMeasurementsGridLayout.addWidget(self.PybraneMemMakerMeasurementsLabel, 0, 0, 1, 2)

        self.PybraneMemMakerFinalZLabel = QtWidgets.QLabel(self.PybraneMemMakerMeasurmentsWidget)
        self.PybraneMemMakerFinalZLabel.setObjectName("PybraneMemMakerFinalZLabel")
        self.PybraneMemMakerMeasurementsGridLayout.addWidget(self.PybraneMemMakerFinalZLabel, 8, 0, 1, 1)

        self.PybraneMemMakerSpacingLabel = QtWidgets.QLabel(self.PybraneMemMakerMeasurmentsWidget)
        self.PybraneMemMakerSpacingLabel.setObjectName("PybraneMemMakerSpacingLabel")

# === Membrane Maker : Measurement Inputs ===
        self.PybraneMemMakerXSpinBox = QtWidgets.QDoubleSpinBox(self.PybraneMemMakerMeasurmentsWidget)
        self.PybraneMemMakerXSpinBox.setObjectName("PybraneMemMakerXSpinBox")
        self.PybraneMemMakerMeasurementsGridLayout.addWidget(self.PybraneMemMakerXSpinBox, 1, 1, 1, 1)

        self.PybraneMemMakerYSpinBox = QtWidgets.QDoubleSpinBox(self.PybraneMemMakerMeasurmentsWidget)
        self.PybraneMemMakerYSpinBox.setObjectName("PybraneMemMakerYSpinBox")
        self.PybraneMemMakerMeasurementsGridLayout.addWidget(self.PybraneMemMakerYSpinBox, 2, 1, 1, 1)

        self.PybraneMemMakerZSpinBox = QtWidgets.QDoubleSpinBox(self.PybraneMemMakerMeasurmentsWidget)
        self.PybraneMemMakerZSpinBox.setObjectName("PybraneMemMakerZSpinBox")
        self.PybraneMemMakerMeasurementsGridLayout.addWidget(self.PybraneMemMakerZSpinBox, 4, 1, 1, 1)

        self.PybraneMemMakerFinalZSpinBox = QtWidgets.QDoubleSpinBox(self.PybraneMemMakerMeasurmentsWidget)
        self.PybraneMemMakerFinalZSpinBox.setObjectName("PybraneMemMakerFinalZSpinBox")
        self.PybraneMemMakerMeasurementsGridLayout.addWidget(self.PybraneMemMakerFinalZSpinBox, 8, 1, 1, 1)

        self.PybraneMemMakerSpacingSpinBox = QtWidgets.QDoubleSpinBox(self.PybraneMemMakerMeasurmentsWidget)
        self.PybraneMemMakerSpacingSpinBox.setObjectName("PybraneMemMakerSpacingSpinBox")
        self.PybraneMemMakerMeasurementsGridLayout.addWidget(self.PybraneMemMakerSpacingSpinBox, 7, 1, 1, 1)

# === Membrane Maker : Measurement Layout Completion ===
        self.PybraneMemMakerMeasurementsGridLayout.addWidget(self.PybraneMemMakerSpacingLabel, 7, 0, 1, 1)
        self.PybraneMemMakerMainGridLayout.addWidget(self.PybraneMemMakerMeasurmentsWidget, 1, 0, 1, 1)

# === Membrane Maker : Files Section ===
        self.PybraneMemMakerFilesWidget = QtWidgets.QWidget(self.PybraneMemMakerTab)
        self.PybraneMemMakerFilesWidget.setObjectName("PybraneMemMakerFilesWidget")
        self.PybraneMemMakerFilesGridLayout = QtWidgets.QGridLayout(self.PybraneMemMakerFilesWidget)
        self.PybraneMemMakerFilesGridLayout.setObjectName("PybraneMemMakerFilesGridLayout")

        self.PybraneMemMakerFilesLabel = QtWidgets.QLabel(self.PybraneMemMakerFilesWidget)
        self.PybraneMemMakerFilesLabel.setObjectName("PybraneMemMakerFilesLabel")
        self.PybraneMemMakerFilesGridLayout.addWidget(self.PybraneMemMakerFilesLabel, 0, 0, 1, 2)

        self.PybraneMemMakerMemLoadButton = QtWidgets.QPushButton(self.PybraneMemMakerFilesWidget)
        self.PybraneMemMakerMemLoadButton.setObjectName("PybraneMemMakerMemLoadButton")
        self.PybraneMemMakerFilesGridLayout.addWidget(self.PybraneMemMakerMemLoadButton, 1, 0, 1, 1)

        self.PybraneMemMakerMemRatioSpinBox1 = QtWidgets.QDoubleSpinBox(self.PybraneMemMakerFilesWidget)
        self.PybraneMemMakerMemRatioSpinBox1.setObjectName("PybraneMemMakerMemRatioSpinBox1")
        self.PybraneMemMakerFilesGridLayout.addWidget(self.PybraneMemMakerMemRatioSpinBox1, 1, 1, 1, 1)

        self.PybraneMemMakerProteinLoadButton = QtWidgets.QPushButton(self.PybraneMemMakerFilesWidget)
        self.PybraneMemMakerProteinLoadButton.setObjectName("PybraneMemMakerProteinLoadButton")
        self.PybraneMemMakerFilesGridLayout.addWidget(self.PybraneMemMakerProteinLoadButton, 2, 0, 1, 1)

        self.PybraneMemMakerProteinRatioSpinBox = QtWidgets.QDoubleSpinBox(self.PybraneMemMakerFilesWidget)
        self.PybraneMemMakerProteinRatioSpinBox.setObjectName("PybraneMemMakerProteinRatioSpinBox")
        self.PybraneMemMakerFilesGridLayout.addWidget(self.PybraneMemMakerProteinRatioSpinBox, 2, 1, 1, 1)

        self.PybraneMemMakerProteinRadioButton = QtWidgets.QRadioButton(self.PybraneMemMakerFilesWidget)
        self.PybraneMemMakerProteinRadioButton.setObjectName("PybraneMemMakerProteinRadioButton")
        self.PybraneMemMakerFilesGridLayout.addWidget(self.PybraneMemMakerProteinRadioButton, 3, 0, 1, 2)

        self.PybraneMemMakerMainGridLayout.addWidget(self.PybraneMemMakerFilesWidget, 1, 1, 1, 1)

# === Membrane Maker : Start Button ===
        self.PybraneMemMakerStartButton = QtWidgets.QPushButton(self.PybraneMemMakerTab)
        self.PybraneMemMakerStartButton.setObjectName("PybraneMemMakerStartButton")
        self.PybraneMemMakerMainGridLayout.addWidget(self.PybraneMemMakerStartButton, 2, 1, 1, 1)

# === Membrane Maker : Tab Addition ===
        self.PybraneCenterWidget.addTab(self.PybraneMemMakerTab, "")

# === Simulation Setup : Tab Initialization ===
        self.PybraneSimSetUpTab = QtWidgets.QWidget()
        self.PybraneSimSetUpTab.setObjectName("PybraneSimSetUpTab")
        self.PybraneSimSetUpGridLayout = QtWidgets.QGridLayout(self.PybraneSimSetUpTab)
        self.PybraneSimSetUpGridLayout.setObjectName("PybraneSimSetUpGridLayout")

# === Simulation Setup : Top Text Browser ===

        self.PybraneSimSetUp3DJSViewer = QWebEngineView()
        self.PybraneSimSetUp3DJSViewer.load(QUrl.fromLocalFile(html_path))
        self.PybraneSimSetUp3DJSViewer.setObjectName("PybraneSimSetUp3DJSViewer")
        self.PybraneSimSetUpGridLayout.addWidget(self.PybraneSimSetUp3DJSViewer, 0, 0, 1, 1)

# === Simulation Setup : Bottom Layout ===
        self.PybraneSimSetUpBottomWidget = QtWidgets.QWidget(self.PybraneSimSetUpTab)
        self.PybraneSimSetUpBottomWidget.setObjectName("PybraneSimSetUpBottomWidget")
        self.PybraneSimSetUpBottomHorizontalLayout = QtWidgets.QHBoxLayout(self.PybraneSimSetUpBottomWidget)
        self.PybraneSimSetUpBottomHorizontalLayout.setObjectName("PybraneSimSetUpBottomHorizontalLayout")

# === Simulation Setup : Bottom Left Section ===
        self.PybraneSimSetUpBottomLeftWidget = QtWidgets.QWidget(self.PybraneSimSetUpBottomWidget)
        self.PybraneSimSetUpBottomLeftWidget.setObjectName("PybraneSimSetUpBottomLeftWidget")
        self.PybraneSimSetUpBottomLeftVerticalLayout = QtWidgets.QVBoxLayout(self.PybraneSimSetUpBottomLeftWidget)
        self.PybraneSimSetUpBottomLeftVerticalLayout.setObjectName("PybraneSimSetUpBottomLeftVerticalLayout")

# === Simulation Setup : File Load Widgets ===
        self.PybraneSimSetUpLoadWidget = QtWidgets.QWidget(self.PybraneSimSetUpBottomLeftWidget)
        self.PybraneSimSetUpLoadWidget.setObjectName("PybraneSimSetUpLoadWidget")
        self.PybraneSimSetUpLoadGridLayout = QtWidgets.QGridLayout(self.PybraneSimSetUpLoadWidget)
        self.PybraneSimSetUpLoadGridLayout.setObjectName("PybraneSimSetUpLoadGridLayout")

        self.PybraneSimSetUpMembraneLabel = QtWidgets.QLabel(self.PybraneSimSetUpLoadWidget)
        self.PybraneSimSetUpMembraneLabel.setObjectName("PybraneSimSetUpMembraneLabel")
        self.PybraneSimSetUpLoadGridLayout.addWidget(self.PybraneSimSetUpMembraneLabel, 0, 0, 1, 1)

        self.PybraneSimSetUpMemLoadButton = QtWidgets.QPushButton(self.PybraneSimSetUpLoadWidget)
        self.PybraneSimSetUpMemLoadButton.setObjectName("PybraneSimSetUpMemLoadButton")
        self.PybraneSimSetUpLoadGridLayout.addWidget(self.PybraneSimSetUpMemLoadButton, 0, 1, 1, 1)

        self.PybraneSimSetUpFFLabel = QtWidgets.QLabel(self.PybraneSimSetUpLoadWidget)
        self.PybraneSimSetUpFFLabel.setObjectName("PybraneSimSetUpFFLabel")
        self.PybraneSimSetUpLoadGridLayout.addWidget(self.PybraneSimSetUpFFLabel, 1, 0, 1, 1)

        self.PybraneSimSetUpFFLoadButton = QtWidgets.QPushButton(self.PybraneSimSetUpLoadWidget)
        self.PybraneSimSetUpFFLoadButton.setObjectName("PybraneSimSetUpFFLoadButton")
        self.PybraneSimSetUpLoadGridLayout.addWidget(self.PybraneSimSetUpFFLoadButton, 1, 1, 1, 1)

        self.PybraneSimSetUpOtherLabel = QtWidgets.QLabel(self.PybraneSimSetUpLoadWidget)
        self.PybraneSimSetUpOtherLabel.setObjectName("PybraneSimSetUpOtherLabel")
        self.PybraneSimSetUpLoadGridLayout.addWidget(self.PybraneSimSetUpOtherLabel, 2, 0, 1, 1)

        self.PybraneSimSetUpOtherLoadButton = QtWidgets.QPushButton(self.PybraneSimSetUpLoadWidget)
        self.PybraneSimSetUpOtherLoadButton.setObjectName("PybraneSimSetUpOtherLoadButton")
        self.PybraneSimSetUpLoadGridLayout.addWidget(self.PybraneSimSetUpOtherLoadButton, 2, 1, 1, 1)

        self.PybraneSimSetUpBottomLeftVerticalLayout.addWidget(self.PybraneSimSetUpLoadWidget)

# === Simulation Setup : Dimensions Widget ===
        self.PybraneSimSetUpSimDimensionsWidget = QtWidgets.QWidget(self.PybraneSimSetUpBottomLeftWidget)
        self.PybraneSimSetUpSimDimensionsWidget.setObjectName("PybraneSimSetUpSimDimensionsWidget")
        self.PybraneSimSetUpSimDimensionsGridLayout = QtWidgets.QGridLayout(self.PybraneSimSetUpSimDimensionsWidget)
        self.PybraneSimSetUpSimDimensionsGridLayout.setObjectName("PybraneSimSetUpSimDimensionsGridLayout" \
        "")

        self.PybraneSimSetUpYSpinBox = QtWidgets.QSpinBox(self.PybraneSimSetUpSimDimensionsWidget)
        self.PybraneSimSetUpYSpinBox.setObjectName("PybraneSimSetUpYSpinBox")
        self.PybraneSimSetUpSimDimensionsGridLayout.addWidget(self.PybraneSimSetUpYSpinBox, 1, 1, 1, 1)
        self.PybraneSimSetUpZSpinBox = QtWidgets.QSpinBox(self.PybraneSimSetUpSimDimensionsWidget)
        self.PybraneSimSetUpZSpinBox.setObjectName("PybraneSimSetUpZSpinBox")
        self.PybraneSimSetUpSimDimensionsGridLayout.addWidget(self.PybraneSimSetUpZSpinBox, 1, 2, 1, 1)
        self.PybraneSimSetUpXSpinBox = QtWidgets.QSpinBox(self.PybraneSimSetUpSimDimensionsWidget)
        self.PybraneSimSetUpXSpinBox.setObjectName("PybraneSimSetUpXSpinBox")
        self.PybraneSimSetUpSimDimensionsGridLayout.addWidget(self.PybraneSimSetUpXSpinBox, 1, 0, 1, 1)
        self.PybraneSimSetUpSimDimensionsLabel = QtWidgets.QLabel(self.PybraneSimSetUpSimDimensionsWidget)
        self.PybraneSimSetUpSimDimensionsLabel.setObjectName("PybraneSimSetUpSimDimensionsLabel")
        self.PybraneSimSetUpSimDimensionsGridLayout.addWidget(self.PybraneSimSetUpSimDimensionsLabel, 0, 0, 1, 3)
        self.PybraneSimSetUpBottomLeftVerticalLayout.addWidget(self.PybraneSimSetUpSimDimensionsWidget)

# === Simulation Setup : Bottom Layout Assembly ===
        self.PybraneSimSetUpBottomHorizontalLayout.addWidget(self.PybraneSimSetUpBottomLeftWidget)
        self.PybraneSimSetUpBottomRightWidget = QtWidgets.QWidget(self.PybraneSimSetUpBottomWidget)
        self.PybraneSimSetUpBottomRightWidget.setObjectName("PybraneSimSetUpBottomRightWidget")
        self.PybraneSimSetUpBottomRightVerticalLayout = QtWidgets.QVBoxLayout(self.PybraneSimSetUpBottomRightWidget)
        self.PybraneSimSetUpBottomRightVerticalLayout.setObjectName("PybraneSimSetUpBottomRightVerticalLayout")

# === Simulation Setup : Bottom Right Widgets ===
        self.PybraneSimSetUpStartButton = QtWidgets.QPushButton(self.PybraneSimSetUpBottomRightWidget)
        self.PybraneSimSetUpStartButton.setObjectName("PybraneSimSetUpStartButton")
        self.PybraneSimSetUpBottomRightVerticalLayout.addWidget(self.PybraneSimSetUpStartButton)
        self.PybraneSimSetUpDebugTextBox = QtWidgets.QTextBrowser(self.PybraneSimSetUpBottomRightWidget)
        self.PybraneSimSetUpDebugTextBox.setObjectName("PybraneSimSetUpDebugTextBox")
        self.PybraneSimSetUpBottomRightVerticalLayout.addWidget(self.PybraneSimSetUpDebugTextBox)
        self.PybraneSimSetUpBottomHorizontalLayout.addWidget(self.PybraneSimSetUpBottomRightWidget)

# === Simulation Setup : Final Layout Addition ===
        self.PybraneSimSetUpGridLayout.addWidget(self.PybraneSimSetUpBottomWidget, 1, 0, 1, 1)
        self.PybraneCenterWidget.addTab(self.PybraneSimSetUpTab, "")

# === Analysis Tab : Initialization ===
        self.PybraneAnalysisTab = QtWidgets.QWidget()
        self.PybraneAnalysisTab.setObjectName("PybraneAnalysisTab")
        self.PybraneAnalysisGridLayout = QtWidgets.QGridLayout(self.PybraneAnalysisTab)
        self.PybraneAnalysisGridLayout.setObjectName("PybraneAnalysisGridLayout")
        # === Analysis Tab : Left Panel ===
        self.PybraneAnalysisLeftWidget = QtWidgets.QWidget(self.PybraneAnalysisTab)
        self.PybraneAnalysisLeftWidget.setObjectName("PybraneAnalysisLeftWidget")
        self.PybraneAnalysisLeftGridLayout = QtWidgets.QGridLayout(self.PybraneAnalysisLeftWidget)
        self.PybraneAnalysisLeftGridLayout.setObjectName("PybraneAnalysisLeftGridLayout")

        # === Analysis Tab : Left Panel - 3D JS Viewer ===
        self.PybraneAnalysis3DJSViewer = QWebEngineView()
        self.PybraneAnalysis3DJSViewer.setObjectName("PybraneAnalysis3DJSViewer")
        self.PybraneAnalysis3DJSViewer.load(QUrl.fromLocalFile(html_path))
        self.PybraneAnalysisLeftGridLayout.addWidget(self.PybraneAnalysis3DJSViewer, 0, 0, 1, 2)

        # === Analysis Tab : Left Panel - Button Holder ===
        self.PybraneAnalysisButtonHolderWidget = QtWidgets.QWidget(self.PybraneAnalysisLeftWidget)
        self.PybraneAnalysisButtonHolderWidget.setObjectName("PybraneAnalysisButtonHolderWidget")
        self.PybraneAnalysisButtonLayout = QtWidgets.QHBoxLayout(self.PybraneAnalysisButtonHolderWidget)
        self.PybraneAnalysisButtonLayout.setObjectName("PybraneAnalysisButtonLayout")

        self.PybraneAnalysisExpandButton = QtWidgets.QPushButton(self.PybraneAnalysisButtonHolderWidget)
        self.PybraneAnalysisExpandButton.setObjectName("PybraneAnalysisExpandButton")
        self.PybraneAnalysisButtonLayout.addWidget(self.PybraneAnalysisExpandButton)

        self.PybraneAnalysisUpdateButton = QtWidgets.QPushButton(self.PybraneAnalysisButtonHolderWidget)
        self.PybraneAnalysisUpdateButton.setObjectName("PybraneAnalysisUpdateButton")
        self.PybraneAnalysisButtonLayout.addWidget(self.PybraneAnalysisUpdateButton)

        self.PybraneAnalysisAdjustButton = QtWidgets.QPushButton(self.PybraneAnalysisButtonHolderWidget)
        self.PybraneAnalysisAdjustButton.setObjectName("PybraneAnalysisAdjustButton")
        self.PybraneAnalysisButtonLayout.addWidget(self.PybraneAnalysisAdjustButton)

        self.PybraneAnalysisLeftGridLayout.addWidget(self.PybraneAnalysisButtonHolderWidget, 1, 0, 1, 2)

        # === Plot 1 ===
        self.PybraneAnalysisPlot1 = genericGraph()
        self.PybraneAnalysisPlot1.setObjectName("PybraneAnalysisPlot1")
        self.PybraneAnalysisLeftGridLayout.addWidget(self.PybraneAnalysisPlot1, 2, 0,1, 2)

        # === Plot 2 ===
        self.PybraneAnalysisPlot2 = genericGraph()
        self.PybraneAnalysisPlot2.setObjectName("PybraneAnalysisPlot2")
        self.PybraneAnalysisLeftGridLayout.addWidget(self.PybraneAnalysisPlot2, 3, 0,1, 2)

        # === Add Left Panel to Main Grid Layout ===
        self.PybraneAnalysisGridLayout.addWidget(self.PybraneAnalysisLeftWidget, 0, 0, 3,2 )


# === Analysis Tab : Right Panel ===
        self.PybraneAnalysisRightWidget = QtWidgets.QWidget(self.PybraneAnalysisTab)
        self.PybraneAnalysisRightWidget.setObjectName("PybraneAnalysisRightWidget")
        self.PybraneAnalysisRightVerticalLayout = QtWidgets.QVBoxLayout(self.PybraneAnalysisRightWidget)
        self.PybraneAnalysisRightVerticalLayout.setObjectName("PybraneAnalysisRightVerticalLayout")
        self.PybraneAnalysisPlot3 = genericGraph()
        self.PybraneAnalysisPlot3.setObjectName("PybraneAnalysisPlot3")
        self.PybraneAnalysisRightVerticalLayout.addWidget(self.PybraneAnalysisPlot3)
        self.PybraneAnalysisPlot4 = genericGraph()
        self.PybraneAnalysisPlot4.setObjectName("PybraneAnalysisPlot4")
        self.PybraneAnalysisRightVerticalLayout.addWidget(self.PybraneAnalysisPlot4)
        self.PybraneAnalysisPlot5 = genericGraph()
        self.PybraneAnalysisPlot5.setObjectName("PybraneAnalysisPlot5")
        self.PybraneAnalysisRightVerticalLayout.addWidget(self.PybraneAnalysisPlot5)
        self.PybraneAnalysisGridLayout.addWidget(self.PybraneAnalysisRightWidget, 0, 2, 3, 2)

# === Analysis Tab : Final Addition to Center Widget ===
        self.PybraneCenterWidget.addTab(self.PybraneAnalysisTab, "")

# === Main Layout : Adding Center Widget ===
        self.PyBRANEAppGridLayout.addWidget(self.PybraneCenterWidget, 0, 1, 1, 1)

# === Main Layout : Adding Stacked Widget ===
        self.AppLayoutsHolderStackedWidget.addWidget(self.PyBRANE)
        self.MainCentralGridLayout.addWidget(self.AppLayoutsHolderStackedWidget, 0, 0, 1, 1)

# === Main Window : Set Central Widget and Menubar Setup ===
        MainWindow.setCentralWidget(self.MainCentralWidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 811, 33))
        self.menubar.setObjectName("menubar")

# === Main Window : Menus Creation ===
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)

# === Main Window : Statusbar Setup ===
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

# === Main Window : Actions Creation ===
        self.actionAboutPyBRANE = QtWidgets.QAction(MainWindow)
        self.actionAboutPyBRANE.setObjectName("actionAboutPyBRANE")
        self.actionAbout_Comp_Chem_College = QtWidgets.QAction(MainWindow)
        self.actionAbout_Comp_Chem_College.setObjectName("actionAbout_Comp_Chem_College")
        self.actionSource_Code = QtWidgets.QAction(MainWindow)
        self.actionSource_Code.setObjectName("actionSource_Code")
        self.actionFAQ = QtWidgets.QAction(MainWindow)
        self.actionFAQ.setObjectName("actionFAQ")
        self.actionFurther_Readings = QtWidgets.QAction(MainWindow)
        self.actionFurther_Readings.setObjectName("actionFurther_Readings")
        self.actionMaximize = QtWidgets.QAction(MainWindow)
        self.actionMaximize.setObjectName("actionMaximize")
        self.actionMinimize = QtWidgets.QAction(MainWindow)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionPyBRANE_General_Settings = QtWidgets.QAction(MainWindow)
        self.actionPyBRANE_General_Settings.setObjectName("actionPyBRANE_General_Settings")
        self.actionPyBRANE_Graph_Settings = QtWidgets.QAction(MainWindow)
        self.actionPyBRANE_Graph_Settings.setObjectName("actionPyBRANE_Graph_Settings")
        self.actionPyBRANE_Key_and_File_Settings = QtWidgets.QAction(MainWindow)
        self.actionPyBRANE_Key_and_File_Settings.setObjectName("actionPyBRANE_Key_and_File_Settings")
        self.actionManage_Comp_Chem_College_Progress = QtWidgets.QAction(MainWindow)
        self.actionManage_Comp_Chem_College_Progress.setObjectName("actionManage_Comp_Chem_College_Progress")
        self.actionComp_Chem_College_Other_Settings = QtWidgets.QAction(MainWindow)
        self.actionComp_Chem_College_Other_Settings.setObjectName("actionComp_Chem_College_Other_Settings")
        self.actionOther_Settings = QtWidgets.QAction(MainWindow)
        self.actionOther_Settings.setObjectName("actionOther_Settings")
        self.actionSwitch_To_PyBRANE = QtWidgets.QAction(MainWindow)
        self.actionSwitch_To_PyBRANE.setObjectName("actionSwitch_To_PyBRANE")
        self.actionSwitch_to_Comp_Chem_College = QtWidgets.QAction(MainWindow)
        self.actionSwitch_to_Comp_Chem_College.setObjectName("actionSwitch_to_Comp_Chem_College")
        self.actionOpen_Molecule_Viewer = QtWidgets.QAction(MainWindow)
        self.actionOpen_Molecule_Viewer.setObjectName("actionOpen_Molecule_Viewer")
        self.actionOpen_Molecule_Editor = QtWidgets.QAction(MainWindow)
        self.actionOpen_Molecule_Editor.setObjectName("actionOpen_Molecule_Editor")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionMain_Menu = QtWidgets.QAction(MainWindow)
        self.actionMain_Menu.setObjectName("actionMain_Menu")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionFeedback = QtWidgets.QAction(MainWindow)
        self.actionFeedback.setObjectName("actionFeedback")

# === Main Window : Adding Actions to Menus ===
        self.menuFile.addAction(self.actionQuit)
        self.menuFile.addAction(self.actionMain_Menu)
        self.menuSettings.addAction(self.actionPyBRANE_General_Settings)
        self.menuSettings.addAction(self.actionPyBRANE_Graph_Settings)
        self.menuSettings.addAction(self.actionPyBRANE_Key_and_File_Settings)
        self.menuSettings.addAction(self.actionOther_Settings)
        self.menuWindow.addAction(self.actionMaximize)
        self.menuWindow.addAction(self.actionMinimize)
        self.menuWindow.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionAboutPyBRANE)
        self.menuHelp.addAction(self.actionSource_Code)
        self.menuHelp.addAction(self.actionFAQ)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionFeedback)

# === Main Window : Adding Menus to Menubar ===
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

# === Main Window : Final Setup Calls and Connections ===
        self.retranslateUi(MainWindow)
        self.AppLayoutsHolderStackedWidget.setCurrentIndex(0)
        self.PybraneNotesAndHelpWidget.setCurrentIndex(2)
        self.PybraneHelpDropdown.setCurrentIndex(0)
        self.PybraneLeftWidget.setCurrentIndex(1)
        self.PybraneCenterWidget.setCurrentIndex(2)
        self.PybraneMolViewerViewHolderWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyBRANE: Python Based Research and Analysis Engine"))

# === Homescreen Text and Buttons ===
        self.HomescreenLoadPybraneButton.setText(_translate("MainWindow", "Load PyBRANE"))
        self.HomescreenOpenManualButton.setText(_translate("MainWindow", "Open PyBRANE Manual "))
        self.HomescreenSettingsButton.setText(_translate("MainWindow", "Settings"))
        self.HomescreenCreditsButton.setText(_translate("MainWindow", "Credits/Source/License"))
        
# === Notes and Help Tabs Text ===        
        self.PybraneNotesTextBox.setPlainText(_translate("MainWindow", "You can edit this text for notes!"))
        self.PybraneNotesAndHelpWidget.setTabText(self.PybraneNotesAndHelpWidget.indexOf(self.PybraneNotesWidget), _translate("MainWindow", "Notes"))
        
# === Help Dropdown Items ===        
        # self.PybraneHelpDropdown.setItemText(self.PybraneHelpDropdown.indexOf(self.PybraneOverviewHelpWidget), _translate("MainWindow", "Overview"))
        # #self.PybraneHelpDropdown.setItemText(self.PybraneHelpDropdown.indexOf(self.PybraneMDHelpWidget), _translate("MainWindow", "MD Help"))
        # self.PybraneHelpDropdown.setItemText(self.PybraneHelpDropdown.indexOf(self.PybraneBasicHelpWidget), _translate("MainWindow", "PyBrane Basics"))
        # self.PybraneHelpDropdown.setItemText(self.PybraneHelpDropdown.indexOf(self.PybraneFilesHelpWidget), _translate("MainWindow", "Files and Shell"))
        # self.PybraneHelpDropdown.setItemText(self.PybraneHelpDropdown.indexOf(self.PybraneNotesHelpWidget), _translate("MainWindow", "Notes"))
        # self.PybraneHelpDropdown.setItemText(self.PybraneHelpDropdown.indexOf(self.PybraneMichaelHelpWidget), _translate("MainWindow", "Michael"))
        # self.PybraneHelpDropdown.setItemText(self.PybraneHelpDropdown.indexOf(self.PybraneOtherHelpWidget), _translate("MainWindow", "Other"))
        self.PybraneNotesAndHelpWidget.setTabText(self.PybraneNotesAndHelpWidget.indexOf(self.PybraneLessonTab), _translate("MainWindow", "Learn"))
        self.PybraneLessonTabLevelLabel.setText(_translate("MainWindow", "Level"))
        self.PybraneLessonTabUnitLabel.setText(_translate("MainWindow", "Unit"))
        self.PybraneLessonTabLessonLabel.setText(_translate("MainWindow", "Lesson"))
        
# === Michael Tab and Buttons ===        
        self.PybraneMichaelEnterButton.setText(_translate("MainWindow", "↩"))
        self.PybraneNotesAndHelpWidget.setTabText(self.PybraneNotesAndHelpWidget.indexOf(self.PybraneMichaelTab), _translate("MainWindow", "Michael"))

# === Search Labels and Buttons ===
        self.PybraneChemSpiLabel.setText(_translate("MainWindow", "ChemSpi"))
        self.PybraneChemSpiSearchButton.setText(_translate("MainWindow", "Search"))
        self.PybraneWikipediaLabel.setText(_translate("MainWindow", "Wikipedia"))
        self.PybraneWikipediaSearchButton.setText(_translate("MainWindow", "Search"))
        self.PybranePDBLabel.setText(_translate("MainWindow", "PDB"))
        self.PybranePDBSearchButton.setText(_translate("MainWindow", "Search"))
        self.PybraneMemBankLabel.setText(_translate("MainWindow", "MemBank"))
        self.PybraneMemBankSearchButton.setText(_translate("MainWindow", "Search"))

# === Left Widget Tabs ===
        self.PybraneLeftWidget.setTabText(self.PybraneLeftWidget.indexOf(self.PybraneFileTab), _translate("MainWindow", "Files"))
        self.PybraneShellEnterButton.setText(_translate("MainWindow", "↩"))
        self.PybraneLeftWidget.setTabText(self.PybraneLeftWidget.indexOf(self.PybraneShellTab), _translate("MainWindow", "Shell"))

# === Molecule Viewer Tabs and Buttons ===        
        self.PybraneMolViewerViewHolderWidget.setTabText(self.PybraneMolViewerViewHolderWidget.indexOf(self.PybraneMolViewer3DViewWidget), _translate("MainWindow", "3D View"))
        self.PybraneMolViewerViewHolderWidget.setTabText(self.PybraneMolViewerViewHolderWidget.indexOf(self.PybraneMolViewer2DViewWidget), _translate("MainWindow", "2D View"))
        self.PybraneMolViewerFileLabel.setText(_translate("MainWindow", "File"))
        self.PybraneMolViewerSaveFileButton.setText(_translate("MainWindow", "Save File"))
        self.PybraneMolViewerImportSmilesButton.setText(_translate("MainWindow", "Import SMILES"))
        self.PybraneMolViewerLoadPDBButon.setText(_translate("MainWindow", "Load PDB"))
        self.PybraneMolViewerEditLabel.setText(_translate("MainWindow", "Edit"))
        self.PybraneMolViewerEditAtomsButton.setText(_translate("MainWindow", "Edit Atoms"))
        self.PybraneMolViewerEditBondsButton.setText(_translate("MainWindow", "Edit Bonds"))
        self.PybraneMolViewerEditApperanceButton.setText(_translate("MainWindow", "Edit Apperance"))
        self.PybraneMolViewerMiscLabel.setText(_translate("MainWindow", "Miscallaneous"))
        self.PybraneMolViewerSwitchDisplayButton.setText(_translate("MainWindow", "Switch Display"))
        self.PybraneMolViewerSwitchFilesButton.setText(_translate("MainWindow", "Switch Files"))
        self.PybraneMolViewerExamplesButton.setText(_translate("MainWindow", "Examples"))
        self.PybraneCenterWidget.setTabText(self.PybraneCenterWidget.indexOf(self.PybraneMolViewerTab), _translate("MainWindow", "2D Molecule Designer"))

# === Membrane Maker Labels, Buttons, and Debug Text ===
        self.PybraneMemMakerDebugTextBox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Output goes here....</p></body></html>"))
        self.PybraneMemMakerXLabel.setText(_translate("MainWindow", "X"))
        self.PybraneMemMakerYLabel.setText(_translate("MainWindow", "Y"))
        self.PybraneMemMakerZLabel.setText(_translate("MainWindow", "Z"))
        self.PybraneMemMakerMeasurementsLabel.setText(_translate("MainWindow", "Measurments"))
        self.PybraneMemMakerFinalZLabel.setText(_translate("MainWindow", "Final Height"))
        self.PybraneMemMakerSpacingLabel.setText(_translate("MainWindow", "Spacing"))
        self.PybraneMemMakerFilesLabel.setText(_translate("MainWindow", "Files"))
        self.PybraneMemMakerMemLoadButton.setText(_translate("MainWindow", "Load"))
        self.PybraneMemMakerProteinLoadButton.setText(_translate("MainWindow", "Load"))
        self.PybraneMemMakerProteinRadioButton.setText(_translate("MainWindow", "Click here if loading proteins"))
        self.PybraneMemMakerStartButton.setText(_translate("MainWindow", "START"))
        self.PybraneCenterWidget.setTabText(self.PybraneCenterWidget.indexOf(self.PybraneMemMakerTab), _translate("MainWindow", "Membrane Maker and Inserter"))

# === Simulator Setup Labels and Buttons ===        
        self.PybraneSimSetUpMembraneLabel.setText(_translate("MainWindow", "Membrane"))
        self.PybraneSimSetUpMemLoadButton.setText(_translate("MainWindow", "Load"))
        self.PybraneSimSetUpFFLabel.setText(_translate("MainWindow", "Force Field"))
        self.PybraneSimSetUpFFLoadButton.setText(_translate("MainWindow", "Load"))
        self.PybraneSimSetUpOtherLabel.setText(_translate("MainWindow", "Other"))
        self.PybraneSimSetUpOtherLoadButton.setText(_translate("MainWindow", "Load"))
        self.PybraneSimSetUpSimDimensionsLabel.setText(_translate("MainWindow", "Simulation dimensions "))
        self.PybraneSimSetUpStartButton.setText(_translate("MainWindow", "Start"))
        self.PybraneCenterWidget.setTabText(self.PybraneCenterWidget.indexOf(self.PybraneSimSetUpTab), _translate("MainWindow", "Simulator SetUp"))
        
# === Analysis Buttons and Tabs ===        
        self.PybraneAnalysisExpandButton.setText(_translate("MainWindow", "Expand"))
        self.PybraneAnalysisUpdateButton.setText(_translate("MainWindow", "Update"))
        self.PybraneAnalysisAdjustButton.setText(_translate("MainWindow", "Adjust"))
        self.PybraneCenterWidget.setTabText(self.PybraneCenterWidget.indexOf(self.PybraneAnalysisTab), _translate("MainWindow", "Simulation Output"))

# === Menu Titles and Actions Text ===
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAboutPyBRANE.setText(_translate("MainWindow", "AboutPyBRANE"))
        self.actionAbout_Comp_Chem_College.setText(_translate("MainWindow", "About Comp Chem College"))
        self.actionSource_Code.setText(_translate("MainWindow", "Source Code"))
        self.actionFAQ.setText(_translate("MainWindow", "FAQ"))
        self.actionFurther_Readings.setText(_translate("MainWindow", "Further Readings"))
        self.actionMaximize.setText(_translate("MainWindow", "Maximize"))
        self.actionMinimize.setText(_translate("MainWindow", "Minimize"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionPyBRANE_General_Settings.setText(_translate("MainWindow", "PyBRANE General Settings"))
        self.actionPyBRANE_Graph_Settings.setText(_translate("MainWindow", "PyBRANE Graph Settings"))
        self.actionPyBRANE_Key_and_File_Settings.setText(_translate("MainWindow", "PyBRANE Key and File Settings"))
        self.actionManage_Comp_Chem_College_Progress.setText(_translate("MainWindow", "Manage Comp Chem College Progress"))
        self.actionComp_Chem_College_Other_Settings.setText(_translate("MainWindow", "Comp Chem College Other Settings"))
        self.actionOther_Settings.setText(_translate("MainWindow", "Other Settings"))
        self.actionSwitch_To_PyBRANE.setText(_translate("MainWindow", "Switch To PyBRANE"))
        self.actionSwitch_to_Comp_Chem_College.setText(_translate("MainWindow", "Switch to Comp Chem College"))
        self.actionOpen_Molecule_Viewer.setText(_translate("MainWindow", "Open Molecule Viewer"))
        self.actionOpen_Molecule_Editor.setText(_translate("MainWindow", "Open Molecule Editor"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionMain_Menu.setText(_translate("MainWindow", "Main Menu"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionFeedback.setText(_translate("MainWindow", "Feedback"))

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_()) 