# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingspopup.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

#===Settings UI Setup===
class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(328, 395)
        self.SettingsMainGridLayout = QtWidgets.QGridLayout(Settings)
        self.SettingsMainGridLayout.setObjectName("SettingsMainGridLayout")

        #===Settings Main Tabs===
        self.SettingsTabWidget = QtWidgets.QTabWidget(Settings)
        self.SettingsTabWidget.setObjectName("SettingsTabWidget")

        #===General Settings Tab: Appearance===
        self.SettingsAppearanceTab = QtWidgets.QWidget()
        self.SettingsAppearanceTab.setObjectName("SettingsAppearanceTab")
        self.SettingsAppearanceTabLayout = QtWidgets.QVBoxLayout(self.SettingsAppearanceTab)
        self.SettingsAppearanceTabLayout.setObjectName("SettingsAppearanceTabLayout")
        
        self.SettingsAppearanceTabWidget = QtWidgets.QWidget(self.SettingsAppearanceTab)
        self.SettingsAppearanceTabWidget.setObjectName("SettingsAppearanceTabWidget")
        self.SettingsAppearanceTabWidgetVerticalLayout = QtWidgets.QVBoxLayout(self.SettingsAppearanceTabWidget)
        self.SettingsAppearanceTabWidgetVerticalLayout.setObjectName("SettingsAppearanceTabWidgetVerticalLayout")
        
        self.SettingsAppearanceTabDefaultButton = QtWidgets.QPushButton(self.SettingsAppearanceTabWidget)
        self.SettingsAppearanceTabDefaultButton.setObjectName("SettingsAppearanceTabDefaultButton")
        self.SettingsAppearanceTabWidgetVerticalLayout.addWidget(self.SettingsAppearanceTabDefaultButton)
        
        self.SettingsAppearanceTabFontLabel = QtWidgets.QLabel(self.SettingsAppearanceTabWidget)
        self.SettingsAppearanceTabFontLabel.setObjectName("SettingsAppearanceTabFontLabel")
        self.SettingsAppearanceTabWidgetVerticalLayout.addWidget(self.SettingsAppearanceTabFontLabel)

        self.SettingsAppearanceTabFontComboBox = QtWidgets.QFontComboBox(self.SettingsAppearanceTabWidget)
        self.SettingsAppearanceTabFontComboBox.setObjectName("SettingsAppearanceTabFontComboBox")
        self.SettingsAppearanceTabWidgetVerticalLayout.addWidget(self.SettingsAppearanceTabFontComboBox)

        self.SettingsAppearanceTabTextSizeBox = QtWidgets.QLabel(self.SettingsAppearanceTabWidget)
        self.SettingsAppearanceTabTextSizeBox.setObjectName("SettingsAppearanceTabTextSizeBox")
        self.SettingsAppearanceTabWidgetVerticalLayout.addWidget(self.SettingsAppearanceTabTextSizeBox)

        self.SettingsAppearanceTabTextSizeSpinBox = QtWidgets.QSpinBox(self.SettingsAppearanceTabWidget)
        self.SettingsAppearanceTabTextSizeSpinBox.setObjectName("SettingsAppearanceTabTextSizeSpinBox")
        self.SettingsAppearanceTabWidgetVerticalLayout.addWidget(self.SettingsAppearanceTabTextSizeSpinBox)

        self.SettingsAppearanceTabStyleSheetLabel = QtWidgets.QLabel(self.SettingsAppearanceTabWidget)
        self.SettingsAppearanceTabStyleSheetLabel.setObjectName("SettingsAppearanceTabStyleSheetLabel")
        self.SettingsAppearanceTabWidgetVerticalLayout.addWidget(self.SettingsAppearanceTabStyleSheetLabel)

        self.SettingsAppearanceTabLoadQSSButton = QtWidgets.QPushButton(self.SettingsAppearanceTabWidget)
        self.SettingsAppearanceTabLoadQSSButton.setObjectName("SettingsAppearanceTabLoadQSSButton")
        self.SettingsAppearanceTabWidgetVerticalLayout.addWidget(self.SettingsAppearanceTabLoadQSSButton)

        self.SettingsAppearanceTabThemesLabel = QtWidgets.QLabel(self.SettingsAppearanceTabWidget)
        self.SettingsAppearanceTabThemesLabel.setObjectName("SettingsAppearanceTabThemesLabel")
        self.SettingsAppearanceTabWidgetVerticalLayout.addWidget(self.SettingsAppearanceTabThemesLabel)

        self.SettingsAppearanceTabThemeComboBox = QtWidgets.QComboBox(self.SettingsAppearanceTabWidget)
        self.SettingsAppearanceTabThemeComboBox.setObjectName("SettingsAppearanceTabThemeComboBox")
        self.SettingsAppearanceTabThemeComboBox.addItem("")
        self.SettingsAppearanceTabThemeComboBox.addItem("")
        self.SettingsAppearanceTabThemeComboBox.addItem("")
        self.SettingsAppearanceTabThemeComboBox.addItem("")
        self.SettingsAppearanceTabThemeComboBox.addItem("")
        self.SettingsAppearanceTabThemeComboBox.addItem("")
        self.SettingsAppearanceTabThemeComboBox.addItem("")
        self.SettingsAppearanceTabThemeComboBox.addItem("")
        self.SettingsAppearanceTabThemeComboBox.addItem("")
        self.SettingsAppearanceTabWidgetVerticalLayout.addWidget(self.SettingsAppearanceTabThemeComboBox)

        self.SettingsAppearanceTabLayout.addWidget(self.SettingsAppearanceTabWidget)

        self.SettingsAppearanceTabRESETALLButton = QtWidgets.QPushButton(self.SettingsAppearanceTab)
        self.SettingsAppearanceTabRESETALLButton.setObjectName("SettingsAppearanceTabRESETALLButton")
        self.SettingsAppearanceTabLayout.addWidget(self.SettingsAppearanceTabRESETALLButton)
        self.SettingsTabWidget.addTab(self.SettingsAppearanceTab, "")

        #===General Settings Tab: Search===
        self.SettingsSearchTab = QtWidgets.QWidget()
        self.SettingsSearchTab.setObjectName("SettingsSearchTab")
        self.SettingsSearchTabLayout = QtWidgets.QVBoxLayout(self.SettingsSearchTab)
        self.SettingsSearchTabLayout.setObjectName("SettingsSearchTabLayout")

        self.SettingsSearchTabWidget = QtWidgets.QWidget(self.SettingsSearchTab)
        self.SettingsSearchTabWidget.setObjectName("SettingsSearchTabWidget")
        self.SettingsSearchTabContentLayout = QtWidgets.QVBoxLayout(self.SettingsSearchTabWidget)
        self.SettingsSearchTabContentLayout.setObjectName("SettingsSearchTabContentLayout")

        self.SettingsSearchTabSearchLabel = QtWidgets.QLabel(self.SettingsSearchTabWidget)
        self.SettingsSearchTabSearchLabel.setObjectName("SettingsSearchTabSearchLabel")
        self.SettingsSearchTabContentLayout.addWidget(self.SettingsSearchTabSearchLabel)

        self.SettingsSearchTabChemSpiKeyLabel = QtWidgets.QLabel(self.SettingsSearchTabWidget)
        self.SettingsSearchTabChemSpiKeyLabel.setObjectName("SettingsSearchTabChemSpiKeyLabel")
        self.SettingsSearchTabContentLayout.addWidget(self.SettingsSearchTabChemSpiKeyLabel)

        self.SettingsSearchTabChemSpiKeyLineEdit = QtWidgets.QLineEdit(self.SettingsSearchTabWidget)
        self.SettingsSearchTabChemSpiKeyLineEdit.setObjectName("SettingsSearchTabChemSpiKeyLineEdit")
        self.SettingsSearchTabContentLayout.addWidget(self.SettingsSearchTabChemSpiKeyLineEdit)

        self.SettingsSearchTabDefaultDirectoryLabel = QtWidgets.QLabel(self.SettingsSearchTabWidget)
        self.SettingsSearchTabDefaultDirectoryLabel.setObjectName("SettingsSearchTabDefaultDirectoryLabel")
        self.SettingsSearchTabContentLayout.addWidget(self.SettingsSearchTabDefaultDirectoryLabel)

        self.SettingsSearchTabDirectoryLineEdit = QtWidgets.QLineEdit(self.SettingsSearchTabWidget)
        self.SettingsSearchTabDirectoryLineEdit.setObjectName("SettingsSearchTabDirectoryLineEdit")
        self.SettingsSearchTabContentLayout.addWidget(self.SettingsSearchTabDirectoryLineEdit)

        self.SettingsMembraneGeneratorTabOpenAIKeyLabel = QtWidgets.QLabel(self.SettingsSearchTabWidget)
        self.SettingsMembraneGeneratorTabOpenAIKeyLabel.setObjectName("SettingsMembraneGeneratorTabOpenAIKeyLabel")
        self.SettingsMembraneGeneratorTabOpenAIKeyLabel.setText("Your OpenAI Key")
        self.SettingsSearchTabContentLayout.addWidget(self.SettingsMembraneGeneratorTabOpenAIKeyLabel)

        self.SettingsMembraneGeneratorTabOpenAIKeyLineEdit = QtWidgets.QLineEdit(self.SettingsSearchTabWidget)
        self.SettingsMembraneGeneratorTabOpenAIKeyLineEdit.setObjectName("SettingsMembraneGeneratorTabOpenAIKeyLineEdit")
        self.SettingsSearchTabContentLayout.addWidget(self.SettingsMembraneGeneratorTabOpenAIKeyLineEdit)

        self.SettingsSearchTabLayout.addWidget(self.SettingsSearchTabWidget)
        self.SettingsTabWidget.addTab(self.SettingsSearchTab, "")

        #===General Settings Tab: Molecular Viewer===
        self.SettingsMolViewerTab = QtWidgets.QWidget()
        self.SettingsMolViewerTab.setObjectName("SettingsMolViewerTab")
        self.SettingsMolViewerTabLayout = QtWidgets.QGridLayout(self.SettingsMolViewerTab)
        self.SettingsMolViewerTabLayout.setObjectName("SettingsMolViewerTabLayout")

        self.SettingsMolViewerTabWidget = QtWidgets.QWidget(self.SettingsMolViewerTab)
        self.SettingsMolViewerTabWidget.setObjectName("SettingsMolViewerTabWidget")
        self.SettingsMolViewerTabContentLayout = QtWidgets.QVBoxLayout(self.SettingsMolViewerTabWidget)
        self.SettingsMolViewerTabContentLayout.setObjectName("SettingsMolViewerTabContentLayout")

        self.SettingsMolViewerTabMolViewerLabel = QtWidgets.QLabel(self.SettingsMolViewerTabWidget)
        self.SettingsMolViewerTabMolViewerLabel.setObjectName("SettingsMolViewerTabMolViewerLabel")
        self.SettingsMolViewerTabContentLayout.addWidget(self.SettingsMolViewerTabMolViewerLabel)

        self.SettingsMolViewerTabDefaultSaveLabel = QtWidgets.QLabel(self.SettingsMolViewerTabWidget)
        self.SettingsMolViewerTabDefaultSaveLabel.setObjectName("SettingsMolViewerTabDefaultSaveLabel")
        self.SettingsMolViewerTabContentLayout.addWidget(self.SettingsMolViewerTabDefaultSaveLabel)

        self.SettingsMolViewerTabSaveFileComboBox = QtWidgets.QComboBox(self.SettingsMolViewerTabWidget)
        self.SettingsMolViewerTabSaveFileComboBox.setObjectName("SettingsMolViewerTabSaveFileComboBox")
        self.SettingsMolViewerTabContentLayout.addWidget(self.SettingsMolViewerTabSaveFileComboBox)
        self.SettingsMolViewerTabSaveFileComboBox.addItem("")
        self.SettingsMolViewerTabSaveFileComboBox.addItem("")
        self.SettingsMolViewerTabSaveFileComboBox.addItem("")
        self.SettingsMolViewerTabSaveFileComboBox.addItem("")
        self.SettingsMolViewerTabSaveFileComboBox.addItem("")
        self.SettingsMolViewerTabSaveFileComboBox.addItem("")

        self.SettingsMolViewerTabDefaultImportLabel = QtWidgets.QLabel(self.SettingsMolViewerTabWidget)
        self.SettingsMolViewerTabDefaultImportLabel.setObjectName("SettingsMolViewerTabDefaultImportLabel")
        self.SettingsMolViewerTabContentLayout.addWidget(self.SettingsMolViewerTabDefaultImportLabel)

        self.SettingsMolViewerTabImportFileComboBox = QtWidgets.QComboBox(self.SettingsMolViewerTabWidget)
        self.SettingsMolViewerTabImportFileComboBox.setObjectName("SettingsMolViewerTabImportFileComboBox")
        self.SettingsMolViewerTabContentLayout.addWidget(self.SettingsMolViewerTabImportFileComboBox)
        self.SettingsMolViewerTabImportFileComboBox.addItem("")
        self.SettingsMolViewerTabImportFileComboBox.addItem("")
        self.SettingsMolViewerTabImportFileComboBox.addItem("")
        self.SettingsMolViewerTabImportFileComboBox.addItem("")
        self.SettingsMolViewerTabImportFileComboBox.addItem("")
        self.SettingsMolViewerTabImportFileComboBox.addItem("")

        self.SettingsMolViewerTabAtomColorsLabel = QtWidgets.QLabel(self.SettingsMolViewerTabWidget)
        self.SettingsMolViewerTabAtomColorsLabel.setObjectName("SettingsMolViewerTabAtomColorsLabel")
        self.SettingsMolViewerTabDefaultImportLabel.setObjectName("SettingsMolViewerTabDefaultImportLabel")
        self.SettingsMolViewerTabContentLayout.addWidget(self.SettingsMolViewerTabDefaultImportLabel)

        # self.SettingsMolViewerTabImportFileComboBox = QtWidgets.QComboBox(self.SettingsMolViewerTabWidget)
        # self.SettingsMolViewerTabImportFileComboBox.setObjectName("SettingsMolViewerTabImportFileComboBox")
        # self.SettingsMolViewerTabContentLayout.addWidget(self.SettingsMolViewerTabImportFileComboBox)
        # self.SettingsMolViewerTabImportFileComboBox.addItem("")
        # self.SettingsMolViewerTabImportFileComboBox.addItem("")
        # self.SettingsMolViewerTabImportFileComboBox.addItem("")
        # self.SettingsMolViewerTabImportFileComboBox.addItem("")
        # self.SettingsMolViewerTabImportFileComboBox.addItem("")
        # self.SettingsMolViewerTabImportFileComboBox.addItem("")

        self.SettingsMolViewerTabAtomColorsLabel = QtWidgets.QLabel(self.SettingsMolViewerTabWidget)
        self.SettingsMolViewerTabAtomColorsLabel.setObjectName("SettingsMolViewerTabAtomColorsLabel")
        self.SettingsMolViewerTabContentLayout.addWidget(self.SettingsMolViewerTabAtomColorsLabel)
        self.SettingsMolViewerTabAtomColorsComboBox = QtWidgets.QComboBox(self.SettingsMolViewerTabWidget)
        self.SettingsMolViewerTabAtomColorsComboBox.setObjectName("SettingsMolViewerTabAtomColorsComboBox")
        self.SettingsMolViewerTabAtomColorsComboBox.addItem("")
        self.SettingsMolViewerTabAtomColorsComboBox.addItem("")
        self.SettingsMolViewerTabAtomColorsComboBox.addItem("")
        self.SettingsMolViewerTabAtomColorsComboBox.addItem("")
        self.SettingsMolViewerTabAtomColorsComboBox.addItem("")
        self.SettingsMolViewerTabAtomColorsComboBox.addItem("")
        self.SettingsMolViewerTabAtomColorsComboBox.addItem("")
        self.SettingsMolViewerTabAtomColorsComboBox.addItem("")
        self.SettingsMolViewerTabAtomColorsComboBox.addItem("")
        self.SettingsMolViewerTabAtomColorsComboBox.addItem("")
        self.SettingsMolViewerTabContentLayout.addWidget(self.SettingsMolViewerTabAtomColorsComboBox)
        
        self.SettingsMolViewerTabStyleLabel = QtWidgets.QLabel(self.SettingsMolViewerTabWidget)
        self.SettingsMolViewerTabStyleLabel.setObjectName("SettingsMolViewerTabStyleLabel")
        self.SettingsMolViewerTabContentLayout.addWidget(self.SettingsMolViewerTabStyleLabel)
        self.SettingsMolViewerTabStyleComboBox = QtWidgets.QComboBox(self.SettingsMolViewerTabWidget)
        self.SettingsMolViewerTabStyleComboBox.setObjectName("SettingsMolViewerTabStyleComboBox")
        self.SettingsMolViewerTabContentLayout.addWidget(self.SettingsMolViewerTabStyleComboBox)

        self.SettingsMolViewerTabStyleComboBox.addItem("")
        self.SettingsMolViewerTabStyleComboBox.addItem("")
        self.SettingsMolViewerTabStyleComboBox.addItem("")
        self.SettingsMolViewerTabStyleComboBox.addItem("")
        self.SettingsMolViewerTabStyleComboBox.addItem("")
        self.SettingsMolViewerTabStyleComboBox.addItem("")
        self.SettingsMolViewerTabStyleComboBox.addItem("")
        self.SettingsMolViewerTabLayout.addWidget(self.SettingsMolViewerTabWidget, 0, 0, 1, 1)
        self.SettingsTabWidget.addTab(self.SettingsMolViewerTab, "")
        self.SettingsMainGridLayout.addWidget(self.SettingsTabWidget, 0, 0, 1, 1)

        self.retranslateUi(Settings)
        self.SettingsTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "PyBRANE Settings"))
        self.SettingsAppearanceTabDefaultButton.setText(_translate("Settings", "Default Appearnce"))
        self.SettingsAppearanceTabFontLabel.setText(_translate("Settings", "Font Family"))
        self.SettingsAppearanceTabTextSizeBox.setText(_translate("Settings", "Text Size"))

        self.SettingsMembraneGeneratorTabOpenAIKeyLabel.setText(_translate("Settings", "Your Open AI Key (optional)"))
        self.SettingsAppearanceTabStyleSheetLabel.setText(_translate("Settings", "Load Style Sheet"))
        self.SettingsAppearanceTabLoadQSSButton.setText(_translate("Settings", "Load QSS"))
        self.SettingsAppearanceTabThemesLabel.setText(_translate("Settings", "Themes"))
        self.SettingsAppearanceTabThemeComboBox.setItemText(0, _translate("Settings", "Default (Light)"))
        self.SettingsAppearanceTabThemeComboBox.setItemText(1, _translate("Settings", "Default (Dark)"))
        self.SettingsAppearanceTabThemeComboBox.setItemText(2, _translate("Settings", "Sci-Fi (Dark)"))
        self.SettingsAppearanceTabThemeComboBox.setItemText(3, _translate("Settings", "Cherry Blossom (Light)"))
        self.SettingsAppearanceTabThemeComboBox.setItemText(4, _translate("Settings", "Neon (Dark)"))
        self.SettingsAppearanceTabThemeComboBox.setItemText(5, _translate("Settings", "Deep Ocean (Dark)"))
        self.SettingsAppearanceTabThemeComboBox.setItemText(6, _translate("Settings", "Sand Storm (Dark)"))
        self.SettingsAppearanceTabThemeComboBox.setItemText(7, _translate("Settings", "Desert Oasis (Light)"))
        self.SettingsAppearanceTabThemeComboBox.setItemText(8, _translate("Settings", "Coral Reef (Light)"))
        self.SettingsAppearanceTabRESETALLButton.setText(_translate("Settings", "RESET ALL SETTINGS"))
        self.SettingsTabWidget.setTabText(self.SettingsTabWidget.indexOf(self.SettingsAppearanceTab), _translate("Settings", "General"))
        self.SettingsSearchTabSearchLabel.setText(_translate("Settings", "Search"))
        self.SettingsSearchTabChemSpiKeyLabel.setText(_translate("Settings", "Chem Spider Key"))
        self.SettingsSearchTabDefaultDirectoryLabel.setText(_translate("Settings", "Default Directory"))
        self.SettingsTabWidget.setTabText(self.SettingsTabWidget.indexOf(self.SettingsSearchTab), _translate("Settings", "Search"))
        self.SettingsMolViewerTabMolViewerLabel.setText(_translate("Settings", "Molecule Viewer"))
        self.SettingsMolViewerTabDefaultSaveLabel.setText(_translate("Settings", "Default Save File Type"))
        self.SettingsMolViewerTabDefaultImportLabel.setText(_translate("Settings", "Default Import File Type"))
        self.SettingsMolViewerTabAtomColorsLabel.setText(_translate("Settings", "Edit Atom Colors"))
        
        self.SettingsMolViewerTabStyleComboBox.setItemText(0, _translate("Settings", "Stick"))
        self.SettingsMolViewerTabStyleComboBox.setItemText(1, _translate("Settings", "Line"))
        self.SettingsMolViewerTabStyleComboBox.setItemText(2, _translate("Settings", "Cross"))
        self.SettingsMolViewerTabStyleComboBox.setItemText(3, _translate("Settings", "Sphere"))
        self.SettingsMolViewerTabStyleComboBox.setItemText(4, _translate("Settings", "Cartoon"))
        self.SettingsMolViewerTabStyleComboBox.setItemText(5, _translate("Settings", "Tube"))
        self.SettingsMolViewerTabStyleComboBox.setItemText(6, _translate("Settings", "Ribbon"))
        self.SettingsMolViewerTabAtomColorsComboBox.setItemText(0, _translate("Settings", "Default"))
        self.SettingsMolViewerTabAtomColorsComboBox.setItemText(1, _translate("Settings", "Jmol"))
        self.SettingsMolViewerTabAtomColorsComboBox.setItemText(2, _translate("Settings", "Green Carbon"))
        self.SettingsMolViewerTabAtomColorsComboBox.setItemText(3, _translate("Settings", "Cyan Carbon"))
        self.SettingsMolViewerTabAtomColorsComboBox.setItemText(4, _translate("Settings", "Magenta Carbon"))
        self.SettingsMolViewerTabAtomColorsComboBox.setItemText(5, _translate("Settings", "Yellow Carbon"))
        self.SettingsMolViewerTabAtomColorsComboBox.setItemText(6, _translate("Settings", "White Carbon"))
        self.SettingsMolViewerTabAtomColorsComboBox.setItemText(7, _translate("Settings", "Orange Carbon"))
        self.SettingsMolViewerTabAtomColorsComboBox.setItemText(8, _translate("Settings", "Light Grey Carbon"))
        self.SettingsMolViewerTabAtomColorsComboBox.setItemText(9, _translate("Settings", "Purple Carbon"))


        self.SettingsMolViewerTabStyleLabel.setText(_translate("Settings", "Display Style"))
        self.SettingsTabWidget.setTabText(self.SettingsTabWidget.indexOf(self.SettingsMolViewerTab), _translate("Settings", "Molecule Viewer"))
        
        self.SettingsMolViewerTabSaveFileComboBox.setItemText(0, _translate("Settings", "PDB"))
        self.SettingsMolViewerTabSaveFileComboBox.setItemText(1, _translate("Settings", "MOL"))
        self.SettingsMolViewerTabSaveFileComboBox.setItemText(2, _translate("Settings", "SDF"))
        self.SettingsMolViewerTabSaveFileComboBox.setItemText(3, _translate("Settings", "InChI"))
        self.SettingsMolViewerTabSaveFileComboBox.setItemText(4, _translate("Settings", "SMILES"))
        self.SettingsMolViewerTabSaveFileComboBox.setItemText(5, _translate("Settings", "TDT"))
        self.SettingsMolViewerTabSaveFileComboBox.setItemText(6, _translate("Settings", "XYZ"))
        self.SettingsMolViewerTabSaveFileComboBox.setItemText(7, _translate("Settings", "TPL"))
        self.SettingsMolViewerTabSaveFileComboBox.setItemText(8, _translate("Settings", "FASTA"))
        self.SettingsMolViewerTabSaveFileComboBox.setItemText(9, _translate("Settings", "SMARTS"))
        self.SettingsMolViewerTabSaveFileComboBox.setItemText(10, _translate("Settings", "HELM"))
        self.SettingsMolViewerTabSaveFileComboBox.setItemText(11, _translate("Settings", "CDXML"))
        self.SettingsMolViewerTabSaveFileComboBox.setItemText(12, _translate("Settings", "MrV"))
        self.SettingsMolViewerTabSaveFileComboBox.setItemText(13, _translate("Settings", "JSON"))

        self.SettingsMolViewerTabImportFileComboBox.setItemText(0, _translate("Settings", "PDB"))
        self.SettingsMolViewerTabImportFileComboBox.setItemText(1, _translate("Settings", "MOL"))
        self.SettingsMolViewerTabImportFileComboBox.setItemText(2, _translate("Settings", "SDF"))
        self.SettingsMolViewerTabImportFileComboBox.setItemText(3, _translate("Settings", "InChI"))
        self.SettingsMolViewerTabImportFileComboBox.setItemText(4, _translate("Settings", "SMILES"))
        self.SettingsMolViewerTabImportFileComboBox.setItemText(5, _translate("Settings", "TDT"))
        self.SettingsMolViewerTabImportFileComboBox.setItemText(6, _translate("Settings", "XYZ"))
        self.SettingsMolViewerTabImportFileComboBox.setItemText(7, _translate("Settings", "TPL"))
        self.SettingsMolViewerTabImportFileComboBox.setItemText(8, _translate("Settings", "FASTA"))
        self.SettingsMolViewerTabImportFileComboBox.setItemText(9, _translate("Settings", "SMARTS"))
        self.SettingsMolViewerTabImportFileComboBox.setItemText(10, _translate("Settings", "HELM"))
        self.SettingsMolViewerTabImportFileComboBox.setItemText(11, _translate("Settings", "CDXML"))
        self.SettingsMolViewerTabImportFileComboBox.setItemText(12, _translate("Settings", "MrV"))


